version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: robis_erp_db
    restart: always
    environment:
      POSTGRES_USER: robis_admin
      POSTGRES_PASSWORD: robis_secret_2025
      POSTGRES_DB: robis_erp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U robis_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
