version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: robis_erp_db
    restart: always
    environment:
      POSTGRES_USER: robis_admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: robis_erp_db
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - robis_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: robis_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@robis.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - robis_network
    depends_on:
      - postgres

networks:
  robis_network:
    driver: bridge

volumes:
  postgres_data:
